# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/airat/Projects/shootEmUp/Engine/Render/CMakeLists.txt))

/Users/airat/Projects/shootEmUp/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -S/Users/airat/Projects/shootEmUp -B/Users/airat/Projects/shootEmUp
