# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/airat/Projects/shootEmUp/Engine/Window/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.27.7/share/cmake/Modules/FeatureSummary.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/SDL2/sdl2-config-version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/SDL2/sdl2-config.cmake))

/Users/airat/Projects/shootEmUp/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -S/Users/airat/Projects/shootEmUp -B/Users/airat/Projects/shootEmUp
